### ISSUE TITLE
Error code C86044CD when installing payload

### ISSUE THREAD

**Issue by adammillerio** [shinyquagsire23/supermysterychunkhax#1]
I am trying to install the payload on a SMD cart via an old 3DS with A9LH on 10.7.0. The first time that I ran the installer, it actually installed the payload onto an eShop copy that was on this device. After removing that eShop copy, I am now getting the error code C86044CD with a "failed to install payload" every time. I have tried clearing the save data in game prior but that did not help.

Any assistance would be appreciated!

**Comment by simonbtomlinson** [comment]
I'm having the same issue trying to install from an A9LH 2DS on 10.7.0. I saw https://github.com/smealum/sploit_installer/issues/2 which is about OOT3D but maybe uses the same underlying stuff? I can't delete my save though, because after the hack failed SMD crashes when it starts.

**Comment by adammillerio** [comment]
Yeah, I found that while researching the error code, but clearing the save data does nothing. They do both use the sploit installer, so I am sure they do share some similarities. I suppose I just wish I had a way of knowing if it is having issues with saving the payload to itself.

Side note, I backed up my SMD save using SVDT prior, so I just restored it using that and it no longer froze on launch.

**Comment by adammillerio** [comment]
So, I just managed to get this working, here's what I ended up doing:
1. Deleted all of my save data on the cart via svdt
2. Copied my save backup onto the cart, you could probably just go and start a new game to the point where it would save to do this
3. Downloaded the 1.0 release from this exact repo (rather than salt_sploit_installer)
4. Put it on the SD card and run

Anyway, it looks like my issue was just that I was using the salt_sploit_installer instead.

**Comment by shinyquagsire23** [comment]
Yeah salt_sploit_installer is currently broken for cartridge-based saves on supermysterychunkhax, for a bit I had that installer linked on smd.salthax.org, but I've since moved it back to this repository's installer which still works.

**Comment by adammillerio** [comment]
Ah, well then that explains it! I've got two 10.7.0 3DS with A9LH now thanks to you 👍

**Comment by dazjo** [comment]
Fixed in upcoming release.
