### ISSUE TITLE
SD Data gone?

### ISSUE THREAD

**Issue by BunnyWarlord** [shinyquagsire23/supermysterychunkhax#2]
Okay, so I successfully hacked Pokémon super mystery dungeon for firmware 10.7.0 32. After it first worked, I turned off my 3DS and added a home brew app. I don't remember what it was called, I think it was something like ctp-http or something. Anyway, I put the SD in and power up, and everything is gone. My apps, my badges, and even my theme. So I take it back out and dig around for the problem, and I find that the DCIM file only has 1 file, labeled 100NIN03. I don't know if I'm correct, put I'm pretty sure there's supposed to be 2. I'm extremely concerned about the amount of data I lost, and I'm kind of desperate for a fix to this. Unfortunately, I did not have a backup of my files, which I'm strongly regretting. Is there a fix? Please help!

**Comment by dazjo** [comment]
The game doesn't even have SD access and is incapable of causing this. This certainly falls outside the reach of supermysterychunkhax.
