### ISSUE TITLE
Question Regarding Save Backups for Other Games

### ISSUE THREAD

**Issue by BunnyWarlord** [shinyquagsire23/supermysterychunkhax#3]
Hello.

Everything is working fine, but I want to use PKHex on my physical copy of Pokemon Alpha Sapphire. However, my Super Mystery Dungeon is _also_ a physical cartridge. Is there a way to backup the save data of my game despite not being able to back it up directly via HANS in the Homebrew launcher?

**Comment by Boured** [comment]
Does your system have Emunand or at least some way of patching signatures?

**Comment by BunnyWarlord** [comment]
I don't think so, because I don't even know what that means tbh. How can I get that?

**Comment by Boured** [comment]
Try using Save Manager, it will extract the save. It should have came with the Homebrew Starter Pack.

**Comment by BunnyWarlord** [comment]
It's not on the Starter kit. '_'

**Comment by Boured** [comment]
It should, download the newest starter out from the Homebrew Launcher homepage, and of it's still not in there I have a copy I will give to you.

**Comment by BunnyWarlord** [comment]
Yeah, I just downloaded it, and everything _but_ the save manager is on it.

**Comment by Boured** [comment]
Yeah I'll send you a copy when I get the time.

**Comment by BunnyWarlord** [comment]
Thanks.

**Comment by Boured** [comment]
https://gbatemp.net/threads/save-data-manager-and-editor-for-firmware-up-to-9-9.396245/

Don't worry, it works with 10.7

**Comment by BunnyWarlord** [comment]
Thanks. I just realized I can swap game cards after homebrew is activated. :)
