### ISSUE TITLE
Red screen / Stuck on Initializing

### ISSUE THREAD

**Issue by KaBombz** [shinyquagsire23/supermysterychunkhax#5]
So the first thing to note is that I am on a stock O3DS XL, running 11.0. I have access to the Homebrew Launcher through oothax, though it's a major pain to get that working currently, so I'm trying to run supermysterychunkhax.
Whenever I launch the installer, nothing happens and I hang on a red screen, forcing me to reset back to the Homebrew launcher. However, if I remove the SD card and put it back in, then launch the installer, it tells me:
"Initializing...
Looks like something went wrong. :("
and on the bottom screen:
"Current status:
Running title is not Pokemon SMD.
Check that the installer XML is on your SD card."
I have a digital copy of SMD, and have tried this with and without a cartridge in the 3DS. I have double checked the SD card, and the installer XML is in the installer folder. No idea what I'm doing wrong.

**Comment by ihaveamac** [comment]
try making a folder at the root called "mmap" and put one of these in for the region of your game:
- [JPN](https://github.com/ihaveamac/9.6-dbgen-xmls/blob/1630c64d05a44c4a1d3bc9fe96b14342284357a8/mmap/0004000000149B00.xml)
- [EUR](https://github.com/ihaveamac/9.6-dbgen-xmls/blob/1630c64d05a44c4a1d3bc9fe96b14342284357a8/mmap/0004000000174400.xml)
- [USA](https://github.com/ihaveamac/9.6-dbgen-xmls/blob/1630c64d05a44c4a1d3bc9fe96b14342284357a8/mmap/0004000000174600.xml)

you can also update your hbmenu: https://citizens.salthax.org/boot.3dsx (or build the source at https://github.com/smealum/3ds_hb_menu)

**Comment by KaBombz** [comment]
Forgot to mention I already tried this fix, I have the folder "mmap" in my root directory with the USA xml file in it.

**Comment by ihaveamac** [comment]
did you also update your boot.3dsx or use the newer hbmenu somehow? and are you using *hax 2.7?

**Comment by KaBombz** [comment]
The boot.3dsx I am using is the one from the latest starter kit, is there a newer version than that I can use? As for *hax 2.7, I'm not sure, how do I verify that? Is it just the entry point to the HB launcher?

**Comment by ihaveamac** [comment]
use the one linked to above (https://citizens.salthax.org/boot.3dsx), and also you can see what version it is when you're starting *hax (e.g. "*hax 2.5 beta", "*hax 2.6 gamma"). you'll want to update your entry point's payload if it's not 2.7.

**Comment by KaBombz** [comment]
Thanks, I'll get back to you once I manage to get oothax to work again.
EDIT: Just remebered, the oothax read 2.6 gamma I believe, but there is no 2.7 payload as far as I am aware? I've used the 10.7 payload, and it hasn't been updated to 11.0 yet, could that be the issue?

**Comment by KaBombz** [comment]
Just confirmed that the issue is indeed with the oothax savegame I have, right now I can only boot into *hax 2.6 gamma, so I have to wait for oothax to be updated. Closing this issue.

**Comment by ihaveamac** [comment]
use the oot3dhax installer to update the payload to 2.7.

**Comment by KaBombz** [comment]
Yeah yellows8 just told me that too, so hopefully I can get it to run sometime tonight. Wish me luck with hardmodding this summer.
