### ISSUE TITLE
Failure to update payload for version (Old3DS) 11-0-0-33 USA

### ISSUE THREAD

**Issue by BunnyWarlord** [shinyquagsire23/supermysterychunkhax#6]
I held select and it brought me to a small menu. I hit update *hax payload. I enter Old3DS 11-0-0-33 USA. It always tells me "Failed to download payload -3 0x0". But then it says "Successfully updated payload". I don't really think it actually updated, because every time the game loads, it shows the 3 Pokeball loading icons, and then both screens go white, and then I get an error message and the system restarts itself. Any workarounds?

**Comment by dazjo** [comment]
Use the 10.7 payload, it works on 11.0. There is no 11.0 payload available yet on the *hax server.
